# Generated by Django 4.1.5 on 2023-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdataaccess',
            name='region',
            field=models.CharField(choices=[('Nagaland', 'Nagaland'), ('Jharkhand', 'Jharkhand'), ('Telangana ', 'Telangana '), ('Meghalaya ', 'Meghalaya '), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Tripura ', 'Tripura '), ('Tamil Nadu ', 'Tamil Nadu '), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Mizoram ', 'Mizoram '), ('Punjab ', 'Punjab '), ('Bihar ', 'Bihar '), ('Rajasthan ', 'Rajasthan '), ('Madhya Pradesh ', 'Madhya Pradesh '), ('Maharashtra', 'Maharashtra'), ('Manipur ', 'Manipur '), ('West Bengal ', 'West Bengal '), ('Haryana ', 'Haryana '), ('Chhattisgarh', 'Chhattisgarh'), ('Uttar Pradesh ', 'Uttar Pradesh '), ('Orissa ', 'Orissa '), ('Goa', 'Goa'), ('Kerala ', 'Kerala '), ('Assam', 'Assam'), ('Karnataka ', 'Karnataka '), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Sikkim ', 'Sikkim '), ('Uttarakhand ', 'Uttarakhand '), ('Andhra Pradesha', 'Andhra Pradesha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='bjp_vote_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='inc_vote_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
