# Generated by Django 4.2.4 on 2023-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voterdataaccess_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingdata',
            name='bjp_vote_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='inc_vote_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='VoterDataAccess',
        ),
    ]
